<?php 
	//Get Territory Form
	echo
	'<form action="#" method="post"> <select name="get_territory">
        <option value="[CN-1]">Cielago North &lt1&gt</option>
        <option value="[CN-2]">Cielago North &lt2&gt</option>
        <option value="[CN-3]">Cielago North &lt3&gt</option>
        <option value="[CD-1]">Cielago Depression &lt1&gt</option>
        <option value="[CD-2]">Cielago Depression &lt2&gt</option>
        <option value="[CD-3]">Cielago Depression &lt3&gt</option>
        <option value="[MER-1]">Meridian &lt1&gt</option>
        <option value="[MER-2]">Meridian &lt2&gt</option>
        <option value="[CS-1]">Cielago South &lt2&gt</option>
        <option value="[CS-2]">Cielago South &lt3&gt</option>
        <option value="[CE-1]">Cielago East &lt2&gt</option>
        <option value="[CE-2]">Cielago East &lt3&gt</option>
        <option value="[HP-1]">Cielago East &lt2&gt</option>
        <option value="[HP-2]">Cielago East &lt3&gt</option>
        <option value="[ARR]">Arrakeen</option>
        <option value="[ARS-1]">Arsunt &lt11&gt</option>
        <option value="[ARS-2]">Arsunt &lt12&gt</option>
        <option value="[BAS]">Basin</option>
        <option value="[BL-1]">Broken Land &lt11&gt</option>
        <option value="[BL-2]">Broken Land &lt12&gt</option>
        <option value="[BOTC]">Blight of the Cliff &lt14&gt</option>
        <option value="[BOTC]">Blight of the Cliff &lt15&gt</option>
        <option value="[CAR]">Carthag</option>
        <option value="[FP]">Funeral Plain</option>
        <option value="[FWE-1]">False Wall East &lt4&gt</option>
        <option value="[FWE-2]">False Wall East &lt5&gt</option>
        <option value="[FWE-3]">False Wall East &lt6&gt</option>
        <option value="[FWE-4]">False Wall East &lt7&gt</option>
        <option value="[FWE-5]">False Wall East &lt8&gt</option>
        <option value="[FWS-1]">False Wall South &lt4&gt</option>
        <option value="[FWS-2]">False Wall South &lt5&gt</option>
        <option value="[FWW-1]">False Wall West &lt16&gt</option>
        <option value="[FWW-2]">False Wall West &lt17&gt</option>
        <option value="[FWW-3]">False Wall West &lt18&gt</option>
        <option value="[GK]">Gara Kulon</option>
        <option value="[HB-1]">Hagga Basin &lt12&gt</option>
        <option value="[HB-2]">Hagga Basin &lt13&gt</option>
        <option value="[HE-1]">Habbanya Erg &lt16&gt</option>
        <option value="[HE-2]">Habbanya Erg &lt17&gt</option>
        <option value="[HITR]">Hole in the Rock</option>
        <option value="[HRF-1]">Habbanya Ridge Flat &lt17&gt</option>
        <option value="[HRF-2]">Habbanya Ridge Flat &lt18&gt</option>
        <option value="[HRS]">Habbanya Ridge Sietch</option>
        <option value="[IB-1]">Imperial Basin &lt9&gt</option>
        <option value="[IB-2]">Imperial Basin &lt10&gt</option>
        <option value="[IB-3]">Imperial Basin &lt11&gt</option>
        <option value="[OG-1]">Old Gap &lt9&gt</option>
        <option value="[OG-2]">Old Gap &lt10&gt</option>
        <option value="[OG-3]">Old Gap &lt11&gt</option>
        <option value="[PB-1]">Plastic Basin &lt12&gt</option> 12},
        <option value="[PB-2]">Plastic Basin &lt13&gt</option> 13},
        <option value="[PB-3]">Plastic Basin &lt14&gt</option> 14},
        <option value="[PM-1]">Pasty Mesa &lt5&gt</option> 5}, 
        <option value="[PM-2]">Pasty Mesa &lt6&gt</option> 6}, 
        <option value="[PM-3]">Pasty Mesa &lt7&gt</option> 7}, 
        <option value="[PM-4]">Pasty Mesa &lt8&gt</option> 8}, 
        <option value="[PS]">Polar Sink</option>
        <option value="[RC]">Red Chasm</option>
        <option value="[RO-1]">Rock Outcroppings &lt13&gt</option>
        <option value="[RO-2]">Rock Outcroppings &lt14&gt</option>
        <option value="[RWW]">Rim Wall West</option>
        <option value="[SM-1]">South Mesa &lt4&gt</option>
        <option value="[SM-2]">South Mesa &lt5&gt</option>
        <option value="[SM-3]">South Mesa &lt6&gt</option>
        <option value="[SM-4]">South Mesa &lt7&gt</option>
        <option value="[SR]">Shaya Ridge</option>
        <option value="[ST]">Seitch Tabr</option>
        <option value="[SW-1]">Shield Wall &lt8&gt</option>
        <option value="[SW-2]">Shield Wall &lt9&gt</option>
        <option value="[TGERF]">The Greater Flat</option>
        <option value="[TGF]">The Great Flat</option>
        <option value="[TME-1]">The Minor Erg &lt5&gt</option>
        <option value="[TME-2]">The Minor Erg &lt6&gt</option>
        <option value="[TME-3]">The Minor Erg &lt7&gt</option>
        <option value="[TME-4]">The Minor Erg &lt8&gt</option>
        <option value="[TSI-1]">Tsimpo &lt11&gt</option>
        <option value="[TSI-2]">Tsimpo &lt12&gt</option>
        <option value="[TSI-3]">Tsimpo &lt13&gt</option>
        <option value="[TS]">Tuek\'s Sietch</option>
        <option value="[WPN-1]">Wind Pass North &lt17&gt</option>
        <option value="[WPN-2]">Wind Pass North &lt18&gt</option>
        <option value="[WP-1]">Wind Pass &lt14&gt</option>
        <option value="[WP-2]">Wind Pass &lt15&gt</option>
        <option value="[WP-3]">Wind Pass &lt16&gt</option>
        <option value="[WP-4]">Wind Pass &lt17&gt</option>
        <option value="[OFF]">Off Planet"</option>
        <option value="[TANKS]">Tanks"</option>
	</select> 
	<input type="submit" value="Submit">
	</form>';
?>
